FROM node:alpine

WORKDIR /app

COPY ./package.json .
COPY ./truffle-config.js .
COPY contracts ./contracts/
COPY ./migrations ./migrations/

RUN npm i
RUN npm install -g truffle@5.1.65

CMD ["truffle","migrate", "--reset"]
