FROM node:alpine

WORKDIR /app

RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

RUN npm install -g ganache-cli

CMD ["ganache-cli","-h","0.0.0.0", "--networkId", "2020"]
